"""phase 6 csat rating columns

Revision ID: 0868896c36ce
Revises: 844ec0591727
Create Date: 2026-07-23 07:49:39.358973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0868896c36ce'
down_revision: Union[str, None] = '844ec0591727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('csat_rating', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('csat_comment', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('csat_submitted_at', sa.DateTime(timezone=True), nullable=True))
    # Two recurring autogenerate false-positives omitted for SQLite portability
    # (same as prior migrations): the no-op ALTER COLUMN on tickets.triage_outcome
    # (native_enum=False -> plain VARCHAR, no DB constraint), and the
    # create_foreign_key for merged_into_id -> tickets.id (SQLite can't add a FK
    # via ALTER; the column stays an FK at the ORM level).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'csat_submitted_at')
    op.drop_column('tickets', 'csat_comment')
    op.drop_column('tickets', 'csat_rating')
    # ### end Alembic commands ###
