"""add sentiment field and llm triage enum values

Revision ID: 2908c48965b2
Revises: 8bbb2eeccb26
Create Date: 2026-07-22 21:32:27.104303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2908c48965b2'
down_revision: Union[str, None] = '8bbb2eeccb26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, then hand-adjusted ###
    op.add_column('tickets', sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'ANGRY', name='sentimentlabel', native_enum=False), nullable=True))
    # NOTE: autogenerate also proposed an ALTER COLUMN on tickets.triage_outcome
    # to widen its Enum's allowed Python values (adding LOW_CONFIDENCE). It's
    # omitted here: with native_enum=False the column is plain VARCHAR with no
    # DB-level CHECK constraint, so there is no real schema change to apply —
    # and SQLite doesn't support ALTER COLUMN TYPE at all.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'sentiment')
    # ### end Alembic commands ###
