"""phase 5 canned responses kb articles presence merge mention

Revision ID: 844ec0591727
Revises: d2105682ebd2
Create Date: 2026-07-23 07:26:27.330061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844ec0591727'
down_revision: Union[str, None] = 'd2105682ebd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canned_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kb_articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('keywords', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_presence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'user_id', name='uq_presence_ticket_user')
    )
    op.add_column('tickets', sa.Column('merged_into_id', sa.String(), nullable=True))
    # Two autogenerate suggestions omitted for SQLite portability:
    #  - the ALTER COLUMN on tickets.triage_outcome (same no-op VARCHAR widening
    #    seen in prior migrations; native_enum=False means no DB constraint).
    #  - op.create_foreign_key on merged_into_id -> tickets.id. SQLite cannot
    #    add a FK constraint via ALTER TABLE. The column stays a proper FK at
    #    the ORM level (relationship foreign_keys=[merged_into_id]); on Postgres
    #    a real FK could be added with a batch/alter migration if desired.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'merged_into_id')
    op.drop_table('ticket_presence')
    op.drop_table('kb_articles')
    op.drop_table('canned_responses')
    # ### end Alembic commands ###
