"""add triage rules and ticket triage fields

Revision ID: 8bbb2eeccb26
Revises: 5d8bf3313bcc
Create Date: 2026-07-22 21:18:09.598226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bbb2eeccb26'
down_revision: Union[str, None] = '5d8bf3313bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', name='ticketpriority', native_enum=False), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('evaluation_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tickets', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('triage_outcome', sa.Enum('MATCHED', 'UNMATCHED', name='triageoutcome', native_enum=False), nullable=True))
    op.add_column('tickets', sa.Column('triage_method', sa.Enum('RULE', 'MANUAL', name='triagemethod', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'triage_method')
    op.drop_column('tickets', 'triage_outcome')
    op.drop_column('tickets', 'confidence_score')
    op.drop_table('triage_rules')
    # ### end Alembic commands ###
