"""add sla policies, notifications, ticket sla fields

Revision ID: d2105682ebd2
Revises: 2908c48965b2
Create Date: 2026-07-22 22:20:12.832537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2105682ebd2'
down_revision: Union[str, None] = '2908c48965b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', name='ticketpriority', native_enum=False), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'STANDARD', 'PREMIUM', name='customertier', native_enum=False), nullable=True),
    sa.Column('first_response_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_minutes', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('TICKET_RECEIVED', 'TICKET_IN_PROGRESS', 'TICKET_RESOLVED', 'SLA_AT_RISK', 'SLA_ESCALATED', name='notificationtype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tickets', sa.Column('first_response_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('resolution_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('first_responded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    # NOTE: autogenerate also proposed an ALTER COLUMN on tickets.triage_outcome
    # (same as in the previous migration) — omitted for the same reason: with
    # native_enum=False the column is plain VARCHAR with no DB-level CHECK
    # constraint, so there's no real schema change, and SQLite can't do
    # ALTER COLUMN TYPE anyway.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'escalated_at')
    op.drop_column('tickets', 'first_responded_at')
    op.drop_column('tickets', 'resolution_due_at')
    op.drop_column('tickets', 'first_response_due_at')
    op.drop_table('notifications')
    op.drop_table('sla_policies')
    # ### end Alembic commands ###
